config/routes.rb
Debareta::Application.routes.draw do
  devise_for :users

  resources :bars
  
  resources :users

  
  
  root :to => "home#index"    
  

end

app/models/bar.rb
class Bar < ActiveRecord::Base
  attr_accessible :address, :business_hours, :city, :country, :created_at, :description, :facebook_profile, :latidude, :longitude, :name, :postalcode, :province, :twitter_profile, :bar_type, :updated_at, :webpage, :photo, :tag_list
  
  acts_as_taggable
  acts_as_taggable_on :tags
  
  validates :name,  
            :presence   => true,
            :length     => { :maximum => 255 }
  validates_uniqueness_of :name        
  validates :address, 
            :presence   => true,
            :length     => { :maximum => 255 }                  
  validates :city, 
            :presence   => true,
            :length     => { :maximum => 255 } 
  validates :province, 
            :presence   => true,
            :length     => { :maximum => 255 } 
  validates :country, 
            :presence   => true,
            :length     => { :maximum => 255 } 
  validates :postalcode, 
            :presence   => true,
            :length     => { :maximum => 255 }                                       
  validates :latidude, 
            :presence   => true,
            :length     => { :maximum => 255 }
  validates :longitude, 
            :presence   => true,
            :length     => { :maximum => 255 } 
  validates :description, 
            :length     => { :maximum => 140 } 
  validates :tag_list, 
            :presence   => true,
            :length     => { :maximum => 255 }        
          
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>", :minithumb => "75x75" }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login
  attr_accessible :login
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
before_filter :authenticate_user!
  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])
    @bar.created_at = DateTime.now
    @bar.updated_at = DateTime.now
    @bar.tag_list = params[:bar][:tag_list]
    
    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, :notice => 'Bar was successfully created.' }
        format.json { render :json => @bar, :status => :created, :location => @bar }
      else
        format.html { render :action => "new" }
        format.json { render :json => @bar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])
    @bar.updated_at = DateTime.now

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, :notice => 'Bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  
  #
  # Use this to wrap view elements that the user can't access.
  # !! Note: this is an *interface*, not *security* feature !!
  # You need to do all access control at the controller level.
  #
  # Example:
  # <%= if_authorized?(:index,   User)  do link_to('List all users', users_path) end %> |
  # <%= if_authorized?(:edit,    @user) do link_to('Edit this user', edit_user_path) end %> |
  # <%= if_authorized?(:destroy, @user) do link_to 'Destroy', @user, :confirm => 'Are you sure?', :method => :delete end %> 
  #
  #
  def if_authorized?(action, resource, &block)
    if authorized?(action, resource)
      yield action, resource
    end
  end

  #
  # Link to user's page ('users/1')
  #
  # By default, their login is used as link text and link title (tooltip)
  #
  # Takes options
  # * :content_text => 'Content text in place of user.login', escaped with
  #   the standard h() function.
  # * :content_method => :user_instance_method_to_call_for_content_text
  # * :title_method => :user_instance_method_to_call_for_title_attribute
  # * as well as link_to()'s standard options
  #
  # Examples:
  #   link_to_user @user
  #   # => <a href="/users/3" title="barmy">barmy</a>
  #
  #   # if you've added a .name attribute:
  #  content_tag :span, :class => :vcard do
  #    (link_to_user user, :class => 'fn n', :title_method => :login, :content_method => :name) +
  #          ': ' + (content_tag :span, user.email, :class => 'email')
  #   end
  #   # => <span class="vcard"><a href="/users/3" title="barmy" class="fn n">Cyril Fotheringay-Phipps</a>: <span class="email">barmy@blandings.com</span></span>
  #
  #   link_to_user @user, :content_text => 'Your user page'
  #   # => <a href="/users/3" title="barmy" class="nickname">Your user page</a>
  #
  def link_to_user(user, options={})
    raise "Invalid user" unless user
    options.reverse_merge! :content_method => :login, :title_method => :login, :class => :nickname
    content_text      = options.delete(:content_text)
    content_text    ||= user.send(options.delete(:content_method))
    options[:title] ||= user.send(options.delete(:title_method))
    link_to h(content_text), user_path(user), options
  end

  #
  # Link to login page using remote ip address as link content
  #
  # The :title (and thus, tooltip) is set to the IP address 
  #
  # Examples:
  #   link_to_login_with_IP
  #   # => <a href="/login" title="169.69.69.69">169.69.69.69</a>
  #
  #   link_to_login_with_IP :content_text => 'not signed in'
  #   # => <a href="/login" title="169.69.69.69">not signed in</a>
  #
  def link_to_login_with_IP content_text=nil, options={}
    ip_addr           = request.remote_ip
    content_text    ||= ip_addr
    options.reverse_merge! :title => ip_addr
    if tag = options.delete(:tag)
      content_tag tag, h(content_text), options
    else
      link_to h(content_text), login_path, options
    end
  end

  #
  # Link to the current user's page (using link_to_user) or to the login page
  # (using link_to_login_with_IP).
  #
  def link_to_current_user(options={})
    if current_user
      link_to_user current_user, options
    else
      content_text = options.delete(:content_text) || 'not signed in'
      # kill ignored options from link_to_user
      [:content_method, :title_method].each{|opt| options.delete(opt)} 
      link_to_login_with_IP content_text, options
    end
  end

end

app/views/bars/_form.html.erb
<%= form_for @bar, :html => { :multipart => true } do |f| %>
  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% @bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <div class="limpiar"></div>
      </ul>
    </div>
  <% end %>

<div class="limpiar"></div>
  <div class="formulario">
    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div class="limpiar"></div>
    <div class="field">
      <%= f.label :province %>
      <%= f.text_field :province %>
    </div>
    <div class="field">
      <%= f.label :country %>
      <%= f.text_field :country %>
    </div>
    <div class="field">
      <%= f.label :postalcode %>
      <%= f.text_field :postalcode %>
    </div>
    <div class="limpiar"></div>
    <div class="field">
      <%= f.label :business_hours %>
      <%= f.text_field :business_hours %>
    </div>
    <div class="field">
      <%= f.label :webpage %>
      <%= f.url_field :webpage %>
    </div>
    <div class="field">
      <%= f.label :twitter_profile %>
      <%= f.url_field :twitter_profile %>
    </div>
    <div class="limpiar"></div>
    <div class="field">
      <%= f.label :facebook_profile %>
      <%= f.url_field :facebook_profile %>
    </div>
    <div class="field">
      <%= f.label :latidude %>
      <%= f.text_field :latidude %>
    </div>
    <div class="field">
      <%= f.label :longitude %>
      <%= f.text_field :longitude %>
    </div>
    <div class="limpiar"></div>
    <div class="field">
      <%= f.label :tag_list, "Tags" %> 
      <%= f.text_field :tag_list %>
      <p>(Add tags separated by ,)</p>
    </div>
    <div class="field">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
     <div class="photo field">
      <label>Bar image</label>
      <%= f.file_field :photo %>
    </div>
  <!--div class="field">
    <.%= f.label :created_at %>
    <.%= f.datetime_select :created_at %>
  </div>
  <div class="field">
    <.%= f.label :updated_at %>
    <.%= f.datetime_select :updated_at %>
  </div-->
    <div class="limpiar"></div>

</div>  
<div class="navbar2">
    <div class="btn-group">
        <div class="btn btn-menu span100 btn-small fuente1 left"> <%= f.submit %></div>
    </div>
</div>


<% end %>

app/views/bars/edit.html.erb
<div class="navbar">
    <div class="btn-group">
        <div class="btn btn-menu span50 btn-small fuente1 left"><%= link_to 'Ver Perfil', @bar %></div>
        <div class="btn btn-menu span50 btn-small fuente1 left"><%= link_to 'Volver', bars_path %></div>
    </div>
</div>

<div class="container">
	<h1 class="nuevoB">Editing bar</h1>

	<%= render 'form' %>
	
</div>

app/views/bars/index.html.erb
<div class="navbar">
    <div class="btn-group">
        <div class="btn btn-menu span100 btn-small fuente1 left"><%= link_to 'Nuevo Bar', new_bar_path %></div>
    </div>
</div>

<div class="container">
    <h1 class="nuevoB">Lista de Bares</h1>
    <div class="tabla">
        <table  class="table table-striped" id="example">
            <thead>
              <tr>
                <th></th>
                <th></th>
                <th></th>
                <th><div class="btn btn-inverse btn-small">Nombre</div></th>
                <th><div class="btn btn-inverse btn-small">Dirección</div></th>
                <th><div class="btn btn-inverse btn-small">Ciudad</div></th>
                <th><div class="btn btn-inverse btn-small">Provincia</div></th>
                <th><div class="btn btn-inverse btn-small">País</div></th>
                <th><div class="btn btn-inverse btn-small">Código Postal</div></th>
                <th><div class="btn btn-inverse btn-small">Descripción</div></th>
                <th><div class="btn btn-inverse btn-small">Tipo</div></th>
                <th><div class="btn btn-inverse btn-small">Web</div></th>
                <th><div class="btn btn-inverse btn-small">Twitter</div></th>
                <th><div class="btn btn-inverse btn-small">Facebook</div></th>
                <th><div class="btn btn-inverse btn-small">Horario</div></th>
                <th><div class="btn btn-inverse btn-small">Latitud</div></th>
                <th><div class="btn btn-inverse btn-small">Longitud</div></th>
                <th><div class="btn btn-inverse btn-small">Creado</div></th>
                <th><div class="btn btn-inverse btn-small">Modificado</div></th>
              </tr>
            </thead>
            <tbody>
        <% @bars.each do |bar| %>
              <tr>
                <td> <div class="btn btn-warning btn-mini"><%= link_to 'Ver', bar %></div></td>
                <td> <div class="btn btn-warning btn-mini"><%= link_to 'Editar', edit_bar_path(bar) %></div></td>
                <td> <div class="btn btn-danger btn-mini"><%= link_to 'Eliminar', bar, :method => :delete, :data => { :confirm => 'Are you sure?' } %></div></td>
                <td><%= bar.name %></td>
                <td><%= bar.address %></td>
                <td><%= bar.city %></td>
                <td><%= bar.province %></td>
                <td><%= bar.country %></td>
                <td><%= bar.postalcode %></td>
                <td><%= bar.description %></td>
                <td><%= bar.type %></td>
                <td><%= bar.webpage %></td>
                <td><%= bar.twitter_profile %></td>
                <td><%= bar.facebook_profile %></td>
                <td><%= bar.business_hours %></td>
                <td><%= bar.latidude %></td>
                <td><%= bar.longitude %></td>
                <td><%= bar.created_at %></td>
                <td><%= bar.updated_at %></td>
              </tr>
        <% end %>
            </tbody>
        </table>
    </div>
    <br />

    <div class="btn btn-menu pull-right margin1">
    <%= link_to 'Nuevo Bar', new_bar_path %>
    </div>
</div>

app/views/bars/new.html.erb
<div class="navbar">
    <div class="btn-group">
        <div class="btn btn-menu span100 btn-small fuente1 left"><%= link_to 'Listado de Bares', bars_path %></div>
    </div>
</div>

<div class="container">
	<h1 class="nuevoB marginB">Nuevo Bareto</h1>
	<%= render 'form' %>
</div>

app/views/bars/show.html.erb
<div class="navbar">
    <div class="btn-group">
        <div class="btn btn-menu span50 btn-small fuente1 left"><%= link_to 'Editar', edit_bar_path(@bar) %></div>
        <div class="btn btn-menu span50 btn-small fuente1 left"><%= link_to 'Volver', bars_path %></div>
    </div>
</div>

<div class="container">
  
  <h1 class="nuevoB">
    <span class="left">Perfíl de <%= @bar.name %></span> 
    <span class="right">
    <%= image_tag @bar.photo.url(:thumb) %><!--he cambiado de :minithumb a :thumb y se ha agrandado un poco pero sería lo suyo saber como hacerlo mas grande sin css porque lo he probado y queda mal-->
  </span><div class="limpiar"></div>
  </h1> 
  
  <p id="notice"><%= notice %></p>
  <div class="accordion"><!--Se repite id, y a lo corregire-->
    <h3 class="field_prefil">Datos generales</h3>
    <div class="field_prefil">
      <p>
        <span class="label_perfil left">Nombre:</span>
        <span classs="right"><%= @bar.name %></span>
      </p>

      <p>
        <span class="label_perfil left">Dirección:</span>
        <span classs="right"><%= @bar.address %></span>
      </p>

      <p>
        <span class="label_perfil left">Ciudad:</span>
        <span classs="right"><%= @bar.city %></span>
      </p>

      <p>
        <span class="label_perfil left">Provincia:</span>
        <span classs="right"><%= @bar.province %></span>
      </p>

      <p>
        <span class="label_perfil left">País:</span>
        <span classs="right"><%= @bar.country %></span>
      </p>

      <p>
        <span class="label_perfil left">Postal code:</span>
        <span classs="right"><%= @bar.postalcode %></span>
      </p>
    </div>
    <h3 class="field_prefil">Web y redes sociales</h3>
    <div class="field_prefil">
      <p>
        <span class="label_perfil left">Web:</span>
        <span classs="right"><%= @bar.webpage %></span>
      </p>

      <p>
        <span class="label_perfil left">Twitter:</span>
        <span classs="right"><%= @bar.twitter_profile %></span>
      </p>

      <p>
        <span class="label_perfil left">Facebook:</span>
        <span classs="right"><%= @bar.facebook_profile %></span>
      </p>
    </div>
   <h3 class="field_prefil">Localización</h3>
    <div class="field_prefil">
      <p>
        <span class="label_perfil left">Latitud:</span>
        <span classs="right"><%= @bar.latidude %></span>
      </p>

      <p>
        <span class="label_perfil left">Longitud:</span>
       <span classs="right"><%= @bar.longitude %></span>
      </p>
    </div>
    <h3 class="field_prefil">Descripción</h3>
    <div class="field_prefil">
      <p>
        <%= @bar.description %>
      </p>
       <p>
        <span class="label_perfil left">Horario:</span>
        <span classs="right"><%= @bar.business_hours %></span>
      </p>
    </div>
    <h3 class="field_prefil">Más info</h3>
    <div class="field_prefil">
      <p>
        <span class="label_perfil left">Tags</span>
        <% @bar.tags.each do |tag| %>
          <span classs="right"> <%= tag.name %> </span>
        <% end %>
      </p>

      <p>
        <span class="label_perfil left">Creado:</span>
        <span classs="right"><%= @bar.created_at.strftime('%d %B %Y') %> (hace <%= distance_of_time_in_words(DateTime.now, @bar.created_at) %>)</span>
      </p>

      <p>
        <span class="label_perfil left">Modificado:</span>
        <span classs="right"><%= @bar.updated_at.strftime('%d %B %Y') %></span>
      </p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="navbar">
    <div class="btn-group">
        <div class="btn btn-menu span50 btn-small fuente1 left"><%= link_to 'Nuevo Bar', new_bar_path %></div>
        <div class="btn btn-menu span50 btn-small fuente1 left"><%= link_to 'Listado de Bares', bars_path %></div>
    </div>
</div>

<div class="container centrado">
	<h2 class="asi">¡¡¡This Is How We Do It!!!</h2>
	<%= image_tag("davidpedo.jpg", :alt => "davidpedo") %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title>Debareta.com</title>
	  	<%= stylesheet_link_tag    "application", :media => "all" %>
	  	<link href='http://fonts.googleapis.com/css?family=Damion' rel='stylesheet' type='text/css'>
	  	<link href='http://fonts.googleapis.com/css?family=Damion|Comfortaa' rel='stylesheet' type='text/css'>
	  	<%= javascript_include_tag "application" %>
	  	<%= csrf_meta_tags %>
	</head>
	
	<body>
		<header>
			<div class="barra1">
			    <h1 class="debareta">DeBaReTa</h1>
			    <h2 class="gestion_bares">GESTIÓN DE BARES</h2>
		    	<div class="limpiar"></div>
		    </div>
		</header>
		<section>
                        <p class=""><%= notice %></p>
                        <p class=""><%= alert %></p>
                        <% if user_signed_in? %>
                          <li>
                          <%= link_to('Logout', destroy_user_session_path) %> | <%= link_to('Edit registration', edit_user_registration_path) %>       
                          </li>
                        <% else %>
                          <li>
                          <%= link_to('Login', new_user_session_path)  %>  | <%= link_to('Register', new_user_registration_path)  %>
                          </li>
                        <% end %>                        
			<%= yield %>
		</section>
		<div class="limpiar"></div>
		<footer>
			<div class="barra1 centrado">
			    <h4>La mejor app de Bares</h4>
		    	<div class="limpiar"></div>
		    </div>
		</footer>
	</body>
</html>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>